---
openapi: 3.0.0
info:
  title: Auth Service
  description: API for authoentication and authorization service
  version: 1.0.0
servers:
- url: https://authorization-authentication-service.onrender.com/api/v1/
  description: SwaggerHub API Auto Mocking
paths:
  /tokens/new:
    post:
      summary: Creates a new token
      requestBody:
        description: "User id, owner of the token"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserId'
        required: true
      responses:
        "201":
          description: Success reponse and token created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "422":
          description: Failed response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityResponse'
  /authorize:
    post:
      summary: Authorize the API request based on header parameter
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
      responses:
        "201":
          description: Success reponse and token created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "422":
          description: Failed response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityResponse'
components:
  securitySchemes:
    Authorization:
      type: apiKey
      in: header
      name: X-Username
  schemas:
    UserId:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
    SuccessResponse:
      type: object
      properties:
        status:
          type: integer
          example: 201
        message:
          type: string
          example: Token was successfully created
    UnprocessableEntityResponse:
      required:
      - error
      - status
      type: object
      properties:
        status:
          type: integer
          example: 422
        error:
          type: string
          example: User not found with id...
