default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['DBURL'] %>
  
test:
  <<: *default
  database: authorization_authentication_service_test

production:
  <<: *default
  url: <%= ENV['DBURL'] %>
